import KeywordTracker, { type TrackedKeyword } from '../keywords/keyword-tracker';

const keywords: TrackedKeyword[] = [
  { id: '1', query: 'خرید نرم افزار سئو', targetPage: 'https://example.com/seo', createdAt: new Date().toISOString(), exact: { provider: 'serper', rank: 2, groupRank: 2, change: -1, resultUrl: 'https://example.com/seo', checkedAt: new Date().toISOString(), device: 'desktop', locationCode: 1 }, exactHistory: [{ date: '2026-09-08', rank: 5 }, { date: '2026-09-09', rank: 4 }, { date: '2026-09-10', rank: 3 }, { date: '2026-09-11', rank: 2 }], exactStatus: 'COMPLETED', exactError: null, action: { priority: 'low', code: 'protect', title: 'حفظ و پایش جایگاه', detail: 'تغییرات رقبا، عنوان و سلامت صفحه را پایش کنید.' } },
  { id: '2', query: 'تحلیل سئو سایت', targetPage: 'https://example.com/analyze', createdAt: new Date().toISOString(), exact: { provider: 'serper', rank: 7, groupRank: 7, change: 4, resultUrl: 'https://example.com/services/seo', checkedAt: new Date().toISOString(), device: 'desktop', locationCode: 1 }, exactHistory: [{ date: '2026-09-08', rank: 4 }, { date: '2026-09-09', rank: 5 }, { date: '2026-09-10', rank: 3 }, { date: '2026-09-11', rank: 7 }], exactStatus: 'COMPLETED', exactError: null, action: { priority: 'urgent', code: 'rank-drop', title: 'بررسی فوری افت رتبه', detail: 'تغییرات اخیر صفحه، رقبا و شکل نتایج گوگل را مقایسه کنید.' } },
  { id: '3', query: 'استراتژی محتوا', targetPage: null, createdAt: new Date().toISOString(), exact: { provider: 'serper', rank: 16, groupRank: 16, change: -2, resultUrl: 'https://example.com/blog/content', checkedAt: new Date().toISOString(), device: 'desktop', locationCode: 1 }, exactHistory: [{ date: '2026-09-08', rank: 24 }, { date: '2026-09-09', rank: 20 }, { date: '2026-09-10', rank: 18 }, { date: '2026-09-11', rank: 16 }], exactStatus: 'COMPLETED', exactError: null, action: { priority: 'medium', code: 'strengthen', title: 'تقویت محتوا و اعتبار', detail: 'شکاف محتوایی و لینک‌های داخلی و خارجی را بررسی کنید.' } },
];

export default function Preview() {
  return <main className="dashboard-shell app-dashboard keyword-page" dir="rtl"><div className="formal-dashboard"><section className="keyword-hero"><div><p className="app-overline">رادار عبارت‌های کلیدی</p><h1>حرکت رتبه‌ها را<br/><em>به تصمیم سئو تبدیل کنید.</em></h1><p>کلمات را با Excel، CSV یا ورود دستی اضافه کنید و جایگاه واقعی دامنه را همراه با اقدام بعدی ببینید.</p></div><div className="keyword-radar" aria-hidden="true"><i/><i/><i/><span><b>۳</b><small>کلمه زیر نظر</small></span></div></section><KeywordTracker projectId="preview" initialKeywords={keywords} settings={{ countryCode: 'ir', languageCode: 'fa', locationName: 'Tehran, Iran', device: 'desktop' }} capabilities={{ mobile: false }} summary={{ tracked: 3, checked: 3, top10: 2, averageRank: 8.3, improved: 2, declined: 1 }} exactRankNote="رتبه دسکتاپ با Serper برای تهران از نتایج واقعی گوگل خوانده می‌شود." exactRankReady/></div></main>;
}
